FROM node:slim

# Step 4.1 - Add container working directory
WORKDIR /app

# Step 4.2 - Copy npm dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# Step 4.3 - Install dependencies
RUN npm install

# Copy app source code

COPY . .

#Expose port and start application

EXPOSE 8080 
# exposes the port

CMD ["npm", "start"]
# runs the npm start command